### ISSUE TITLE
Is it possible to build `qh3` without the vendor stuff?

### ISSUE THREAD

**Issue by kseistrup** [jawah/qh3#23]
I am attempting to build `qh3` from the latest commit (481a16be6f2041717db0cc9d76281cda69285bd6) and fail:

```C
src/qh3/_vendor/pylsqpack/binding.c:4:10: fatal error: lsqpack.h: No such file or directory
    4 | #include "lsqpack.h"
      |          ^~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

I am not a programmer. But does `#include "lsqpack.h"` not mean that the header file is supposed to be in the same directory? It is not to be found in the tree at all, it seems.

However, I am on a Linux box (ArchLinux) that has `python-pyopenssl` and `python-pylsqpack` installed. I wonder if they can make it up for that vendor package I cannot compile?

----

PS: My ultimate goal is to roll a `PKGBUILD` script that lets ArchLinux users install the package from AUR. For now I have a workaround that downloads a binary wheel from PyPI, but building from the sorce would be preferrable.

**Comment by Ousret** [comment]
I understand the use case.
It should be feasible, I will look into it as soon as possible.

**Comment by Ousret** [comment]
So, here is my take on the matter.
I took the time to assess the goal and did some tests on a limited subset of distros.

Unfortunately, we cannot rely on external liblsqpack because most of the time, we have the v2 present where we are bound to the v1 (latest). The build will fail with it. Migrating to the v2 is planned, but not right away.

The intermediary solution is to fetch the [sdist](https://files.pythonhosted.org/packages/71/58/316ccf269181336eac7060fada493b893ec2507e27ccf153d727cb61fe74/qh3-0.15.1.tar.gz) and build from there, it includes the compatible lsqpack  along with xxhash.

Hopefully this will resolve this issue. If so, feel free to close it.
Regards,

**Comment by kseistrup** [comment]
Thanks for your help! :pray:

**Comment by Ousret** [comment]
Head up. The build procedure is going to change.
We no longer require the vendor stuff.

We switched to maturin + rust + clang.

**Comment by kseistrup** [comment]
Thanks for the heads up!

I tried to build the package on a relatively clean ArchLinux box, and it seems that in addition to maturin (that automatically pulls in rust) and clang, I specifically have to install cmake. And then everything runs smoothly.
